name: Publish package to github packages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.PAT_DOCKER_IMAGES }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    #- name: Set environment variable
    #  run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

    - name: Build docker image
      run: make build DB_PASSWORD=${{ secrets.DB_PASSWORD }}

    - name: Publish docker image
      run: make publish